import { getPostDetails, getPosts } from "../../services";
import Head from "next/head";
import { Categories, PostWidget,PostDetail,Author,CommentsForm,Comments } from "../../components";

function PostDetails({ post }) {
   return (
    <div>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto px-10 mb-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
            <div className="col-span-1 lg:col-span-8 ">
                <PostDetail post={post}/>
                <Author author={post.author} />
                <Comments slug={post.slug} />
                <CommentsForm slug={post.slug}/>
            </div>
            <div className="col-span-1 lg:col-span-4 ">
                <div className="relative lg:sticky top-8">
                    <PostWidget slug={post.slug} categories={post.categories.map(category=> category.slug)}/>
                    <Categories/>
                </div>

            </div>
        </div>
      </div>
    </div>
  );
}
export async function getStaticProps({ params }) {
  const post = await getPostDetails(params.slug);
  return {
    props: {
      post,
    },
    revalidate: 10
  };
}

export async function getStaticPaths() {
  const posts = await getPosts();
  return {
    paths: posts.map(({ node: { slug } }) => ({ params: { slug } })),
    fallback: 'blocking',
  };
}
export default PostDetails;
