// import React,{useState} from 'react'
import Head from "next/head";
import { getCategoricalPosts, getCategories } from '../../services'
import { PostCard, PostWidget, Categories } from "../../components";
function CategoricalPosts({posts,slug}) {
//   const [showposts,setShowPosts]=useState(posts)
//   console.log(posts)
//   const handleSearch=(e)=>{
//   if(e.target.value)
//     {
//     setShowPosts(posts.filter(post=>post.title.toLowerCase().includes(e.target.value.toLowerCase())))
//     }else setShowPosts(posts)
// }
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Aljabrak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => (
            <PostCard post={post} key={post.createdAt} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            {/* <PostWidget slug={slug} categories={[slug]} /> */}
            <Categories />
          </div>
        </div>
      </div>
    </div>
  
  );
}

export async function getStaticProps ({params}) {
    const posts = await getCategoricalPosts(params.slug);
    return {
        props: {
            posts,
            slug: params.slug
        },
        revalidate: 10,
    }
}

export async function getStaticPaths() {
    const categories = await getCategories();

    return {
        paths: categories.map(({slug}) => ({params: {slug}})),
        fallback: 'blocking',
        
    }
}

export default CategoricalPosts